
{% set name = "heelo2" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: 4.0
  git_url: https://github.com/ChunjieShawn/pybuild2.git

build:
  number: 0
  script: ""

requirements:
  build:
    - heelo
  host:
    - heelo
    - pip
    - python
  run:
    - heelo
    - python >=3.7

about:
  home: 
  license: BSD
  license_family: BSD
  summary: Composable command line interface toolkit
